# Offense count: 2
Lint/HandleExceptions:
  Exclude:
    - 'lib/foreman_xen/vnc_tunnel.rb'

# Offense count: 2
Lint/RescueException:
  Exclude:
    - 'lib/foreman_xen/vnc_tunnel.rb'

# Offense count: 2
Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'app/models/foreman_xen/xenserver.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: IgnoreEmptyBlocks.
Lint/UnusedBlockArgument:
  Exclude:
    - 'lib/foreman_xen/engine.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: AllowUnusedKeywordArguments, IgnoreEmptyMethods.
Lint/UnusedMethodArgument:
  Exclude:
    - 'app/models/concerns/fog_extensions/xenserver/server.rb'
    - 'app/models/foreman_xen/xenserver.rb'

# Offense count: 5
Lint/UselessAssignment:
  Exclude:
    - 'app/helpers/xen_compute_helper.rb'
    - 'lib/foreman_xen/vnc_tunnel.rb'

# Offense count: 15
Metrics/AbcSize:
  Max: 69

# Offense count: 2
Metrics/BlockNesting:
  Max: 4

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 353

# Offense count: 3
Metrics/CyclomaticComplexity:
  Max: 23

# Offense count: 63
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 120
  Exclude:
    - 'app/helpers/xen_compute_helper.rb'

# Offense count: 20
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 43

# Offense count: 5
Metrics/PerceivedComplexity:
  Max: 24

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, Include.
# SupportedStyles: action, filter
# Include: app/controllers/**/*.rb
Rails/ActionFilter:
  Exclude:
    - 'app/controllers/foreman_xen/snapshots_controller.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: SingleLineConditionsOnly.
Style/ConditionalAssignment:
  Exclude:
    - 'app/models/foreman_xen/xenserver.rb'

# Offense count: 2
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'app/controllers/foreman_xen/snapshots_controller.rb'

# Offense count: 8
Style/IdenticalConditionalBranches:
  Exclude:
    - 'app/controllers/foreman_xen/snapshots_controller.rb'
    - 'app/models/foreman_xen/xenserver.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/MutableConstant:
  Exclude:
    - 'lib/foreman_xen/version.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, MinBodyLength, SupportedStyles.
# SupportedStyles: skip_modifier_ifs, always
Style/Next:
  Exclude:
    - 'app/models/foreman_xen/xenserver.rb'

# Offense count: 5
# Cop supports --auto-correct.
Style/RedundantParentheses:
  Exclude:
    - 'app/controllers/foreman_xen/snapshots_controller.rb'
    - 'lib/foreman_xen/vnc_tunnel.rb'

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: only_raise, only_fail, semantic
Style/SignalException:
  Exclude:
    - 'app/models/foreman_xen/xenserver.rb'
    - 'lib/foreman_xen/vnc_tunnel.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment.
Style/SpaceAroundOperators:
  Exclude:
    - 'app/models/foreman_xen/xenserver.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/UnneededInterpolation:
  Exclude:
    - 'app/models/foreman_xen/xenserver.rb'
