# Offense count: 2
Lint/HandleExceptions:
  Exclude:
    - 'lib/foreman_xen/vnc_tunnel.rb'

# Offense count: 2
Lint/RescueException:
  Exclude:
    - 'lib/foreman_xen/vnc_tunnel.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: IgnoreEmptyBlocks, AllowUnusedKeywordArguments.
Lint/UnusedBlockArgument:
  Exclude:
    - 'lib/foreman_xen/engine.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: AllowUnusedKeywordArguments, IgnoreEmptyMethods.
Lint/UnusedMethodArgument:
  Exclude:
    - 'app/models/concerns/fog_extensions/xenserver/server.rb'
    - 'app/models/foreman_xen/xenserver.rb'

# Offense count: 5
Lint/UselessAssignment:
  Exclude:
    - 'app/helpers/xen_compute_helper.rb'
    - 'lib/foreman_xen/vnc_tunnel.rb'

# Offense count: 16
Metrics/AbcSize:
  Max: 65

# Offense count: 2
# Configuration parameters: CountBlocks.
Metrics/BlockNesting:
  Max: 4

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 368

# Offense count: 3
Metrics/CyclomaticComplexity:
  Max: 12

# Offense count: 21
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 52

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 117

# Offense count: 1
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 6

# Offense count: 4
Metrics/PerceivedComplexity:
  Max: 13

# Offense count: 1
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: format, sprintf, percent
Style/FormatString:
  Exclude:
    - 'app/models/concerns/fog_extensions/xenserver/server.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: brackets
